- name: Disable MySQL defaul version
  ansible.builtin.shell: yum module disable mysql -y


- name: Copy Mysql Repo file
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo
     
- name: Install nysql community server
  ansible.builtin.yum:
    name: mysql-community-server
    state: installed

- name: Start my sql Service
  ansible.builtin.systemd:
    name: mysql   
    state: restarted
    enabled: yes 

- name: Setup Root password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1    
 