- name: Configure Nodejs Repos
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Install NodeJS
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: App Pre-requisites
  ansible.builtin.import_tasks:
    file: app_presentup.yml    

- name: Load NodeJS Dependencies
  ansible.builtin.shell: npm installed
  args:
   chdir: /app

- name: SystemD setup_lts
  ansible.builtin.import_tasks:
   file: systemd_setup.yml   
